-- ===========================================================================
-- SAIPEI POS - full database schema for PostgreSQL (13+)
--
-- Generated from prisma/schema.prisma; table, column and constraint names are
-- identical to what `npm run db:push` creates, so the app works against a
-- database built from either path. 45 tables, 70 foreign keys.
--
-- Usage (empty database):
--   psql "postgresql://saipei:saipei@localhost:5432/saipei_pos" -f prisma/postgres/schema.sql
--   psql "postgresql://saipei:saipei@localhost:5432/saipei_pos" -f prisma/postgres/seed.sql
--
-- Notes
--  * Primary keys are UUIDs generated by Prisma Client; DEFAULT gen_random_uuid()
--    is NOT set so the schema matches Prisma exactly (seed.sql supplies ids).
--  * "updatedAt" columns are maintained by Prisma Client (@updatedAt).
--  * Status/type columns are VARCHAR(30); allowed values live in src/lib/enums.ts.
-- ===========================================================================

-- CreateTable
CREATE TABLE "Role" (
    "id" UUID NOT NULL,
    "name" VARCHAR(80) NOT NULL,
    "description" VARCHAR(255),
    "isSystem" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Role_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Permission" (
    "id" UUID NOT NULL,
    "code" VARCHAR(80) NOT NULL,
    "module" VARCHAR(60) NOT NULL,
    "label" VARCHAR(140) NOT NULL,
    CONSTRAINT "Permission_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "RolePermission" (
    "roleId" UUID NOT NULL,
    "permissionId" UUID NOT NULL,
    CONSTRAINT "RolePermission_pkey" PRIMARY KEY ("roleId", "permissionId")
);

CREATE TABLE "User" (
    "id" UUID NOT NULL,
    "email" VARCHAR(160) NOT NULL,
    "username" VARCHAR(60) NOT NULL,
    "fullName" VARCHAR(140) NOT NULL,
    "phone" VARCHAR(30),
    "passwordHash" VARCHAR(200) NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "lastLoginAt" TIMESTAMP(3),
    "roleId" UUID NOT NULL,
    "branchId" UUID,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "AuditLog" (
    "id" UUID NOT NULL,
    "userId" UUID,
    "action" VARCHAR(60) NOT NULL,
    "entity" VARCHAR(80) NOT NULL,
    "entityId" VARCHAR(80),
    "summary" VARCHAR(400),
    "metadata" TEXT,
    "ipAddress" VARCHAR(60),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Setting" (
    "key" VARCHAR(80) NOT NULL,
    "value" TEXT NOT NULL,
    "group" VARCHAR(40) NOT NULL DEFAULT 'general',
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Setting_pkey" PRIMARY KEY ("key")
);

CREATE TABLE "Branch" (
    "id" UUID NOT NULL,
    "code" VARCHAR(20) NOT NULL,
    "name" VARCHAR(120) NOT NULL,
    "location" VARCHAR(200),
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Branch_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Approval" (
    "id" UUID NOT NULL,
    "entity" VARCHAR(80) NOT NULL,
    "entityId" VARCHAR(80) NOT NULL,
    "reference" VARCHAR(80),
    "status" VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    "requestedBy" VARCHAR(140),
    "actorId" UUID,
    "notes" VARCHAR(400),
    "amount" DECIMAL(18,2),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "decidedAt" TIMESTAMP(3),
    CONSTRAINT "Approval_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Supplier" (
    "id" UUID NOT NULL,
    "code" VARCHAR(30) NOT NULL,
    "name" VARCHAR(160) NOT NULL,
    "type" VARCHAR(30) NOT NULL DEFAULT 'FOREIGN',
    "country" VARCHAR(80),
    "contactName" VARCHAR(120),
    "phone" VARCHAR(40),
    "email" VARCHAR(160),
    "address" VARCHAR(300),
    "taxPin" VARCHAR(40),
    "currency" VARCHAR(3) NOT NULL DEFAULT 'USD',
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Supplier_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "PurchaseOrder" (
    "id" UUID NOT NULL,
    "reference" VARCHAR(40) NOT NULL,
    "supplierId" UUID NOT NULL,
    "orderDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expectedDate" TIMESTAMP(3),
    "currency" VARCHAR(3) NOT NULL DEFAULT 'USD',
    "exchangeRate" DECIMAL(18,6) NOT NULL DEFAULT 1,
    "subtotal" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "taxAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "total" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "status" VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    "notes" VARCHAR(600),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "PurchaseOrder_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "PurchaseOrderLine" (
    "id" UUID NOT NULL,
    "purchaseOrderId" UUID NOT NULL,
    "productId" UUID,
    "description" VARCHAR(300) NOT NULL,
    "quantity" DECIMAL(18,3) NOT NULL,
    "receivedQty" DECIMAL(18,3) NOT NULL DEFAULT 0,
    "unitPrice" DECIMAL(18,4) NOT NULL,
    "lineTotal" DECIMAL(18,2) NOT NULL,
    CONSTRAINT "PurchaseOrderLine_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "SupplierInvoice" (
    "id" UUID NOT NULL,
    "invoiceNumber" VARCHAR(60) NOT NULL,
    "supplierId" UUID NOT NULL,
    "purchaseOrderId" UUID,
    "invoiceDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dueDate" TIMESTAMP(3),
    "currency" VARCHAR(3) NOT NULL DEFAULT 'USD',
    "exchangeRate" DECIMAL(18,6) NOT NULL DEFAULT 1,
    "amount" DECIMAL(18,2) NOT NULL,
    "amountPaid" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "isFinal" BOOLEAN NOT NULL DEFAULT false,
    "status" VARCHAR(30) NOT NULL DEFAULT 'UNPAID',
    "documentUrl" VARCHAR(400),
    "notes" VARCHAR(600),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "SupplierInvoice_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "PurchaseReturn" (
    "id" UUID NOT NULL,
    "reference" VARCHAR(40) NOT NULL,
    "supplierId" UUID NOT NULL,
    "returnDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reason" VARCHAR(400),
    "totalAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PurchaseReturn_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "PurchaseReturnLine" (
    "id" UUID NOT NULL,
    "purchaseReturnId" UUID NOT NULL,
    "productId" UUID NOT NULL,
    "quantity" DECIMAL(18,3) NOT NULL,
    "unitPrice" DECIMAL(18,4) NOT NULL,
    "lineTotal" DECIMAL(18,2) NOT NULL,
    CONSTRAINT "PurchaseReturnLine_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ImportOrder" (
    "id" UUID NOT NULL,
    "reference" VARCHAR(40) NOT NULL,
    "supplierId" UUID NOT NULL,
    "purchaseOrderId" UUID,
    "orderDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "stage" VARCHAR(30) NOT NULL DEFAULT 'ORDER_PLACED',
    "description" VARCHAR(400),
    "currency" VARCHAR(3) NOT NULL DEFAULT 'USD',
    "exchangeRate" DECIMAL(18,6) NOT NULL DEFAULT 1,
    "goodsValue" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "ImportOrder_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Shipment" (
    "id" UUID NOT NULL,
    "reference" VARCHAR(40) NOT NULL,
    "importOrderId" UUID NOT NULL,
    "containerNumber" VARCHAR(40),
    "billOfLading" VARCHAR(60),
    "vesselName" VARCHAR(120),
    "loadingDate" TIMESTAMP(3),
    "departureDate" TIMESTAMP(3),
    "expectedArrival" TIMESTAMP(3),
    "actualArrival" TIMESTAMP(3),
    "portOfLoading" VARCHAR(120),
    "portOfDischarge" VARCHAR(120) NOT NULL DEFAULT 'Mombasa',
    "clearingAgentId" UUID,
    "agentNotifiedAt" TIMESTAMP(3),
    "releasedAt" TIMESTAMP(3),
    "status" VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    "numberOfBales" INTEGER NOT NULL DEFAULT 0,
    "totalWeightKg" DECIMAL(18,3) NOT NULL DEFAULT 0,
    "containerCost" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "notes" VARCHAR(600),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Shipment_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ClearingAgent" (
    "id" UUID NOT NULL,
    "code" VARCHAR(30) NOT NULL,
    "name" VARCHAR(160) NOT NULL,
    "contactName" VARCHAR(120),
    "phone" VARCHAR(40),
    "email" VARCHAR(160),
    "taxPin" VARCHAR(40),
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ClearingAgent_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ImportDocument" (
    "id" UUID NOT NULL,
    "importOrderId" UUID NOT NULL,
    "shipmentId" UUID,
    "type" VARCHAR(30) NOT NULL,
    "reference" VARCHAR(80),
    "issueDate" TIMESTAMP(3),
    "expiryDate" TIMESTAMP(3),
    "fileUrl" VARCHAR(400),
    "notes" VARCHAR(400),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ImportDocument_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "CustomsEntry" (
    "id" UUID NOT NULL,
    "shipmentId" UUID NOT NULL,
    "entryNumber" VARCHAR(60) NOT NULL,
    "entryDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "customsValue" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "importDuty" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "vat" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "idfFee" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "railwayLevy" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "importDeclLevy" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "exciseDuty" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "otherLevies" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "totalTaxes" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "paidAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CustomsEntry_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "LandedCostCharge" (
    "id" UUID NOT NULL,
    "importOrderId" UUID NOT NULL,
    "shipmentId" UUID,
    "category" VARCHAR(30) NOT NULL,
    "description" VARCHAR(300) NOT NULL,
    "currency" VARCHAR(3) NOT NULL DEFAULT 'KES',
    "exchangeRate" DECIMAL(18,6) NOT NULL DEFAULT 1,
    "amount" DECIMAL(18,2) NOT NULL,
    "amountKes" DECIMAL(18,2) NOT NULL,
    "chargeDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isPaid" BOOLEAN NOT NULL DEFAULT false,
    "payeeName" VARCHAR(160),
    "reference" VARCHAR(80),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "LandedCostCharge_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Category" (
    "id" UUID NOT NULL,
    "name" VARCHAR(120) NOT NULL,
    "description" VARCHAR(300),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Category_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Product" (
    "id" UUID NOT NULL,
    "sku" VARCHAR(40) NOT NULL,
    "barcode" VARCHAR(60),
    "name" VARCHAR(200) NOT NULL,
    "description" VARCHAR(500),
    "categoryId" UUID,
    "unit" VARCHAR(30) NOT NULL DEFAULT 'PIECE',
    "costPrice" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "sellingPrice" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "reorderLevel" DECIMAL(18,3) NOT NULL DEFAULT 0,
    "taxRate" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "imageUrl" VARCHAR(400),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Product_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Warehouse" (
    "id" UUID NOT NULL,
    "code" VARCHAR(20) NOT NULL,
    "name" VARCHAR(120) NOT NULL,
    "location" VARCHAR(200),
    "branchId" UUID,
    "isDefault" BOOLEAN NOT NULL DEFAULT false,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Warehouse_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "StockLevel" (
    "id" UUID NOT NULL,
    "productId" UUID NOT NULL,
    "warehouseId" UUID NOT NULL,
    "quantity" DECIMAL(18,3) NOT NULL DEFAULT 0,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "StockLevel_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "StockMovement" (
    "id" UUID NOT NULL,
    "productId" UUID NOT NULL,
    "warehouseId" UUID NOT NULL,
    "type" VARCHAR(30) NOT NULL,
    "quantity" DECIMAL(18,3) NOT NULL,
    "balanceAfter" DECIMAL(18,3) NOT NULL DEFAULT 0,
    "unitCost" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "reference" VARCHAR(80),
    "sourceType" VARCHAR(60),
    "sourceId" VARCHAR(80),
    "userId" UUID,
    "notes" VARCHAR(300),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "StockMovement_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "GoodsReceipt" (
    "id" UUID NOT NULL,
    "reference" VARCHAR(40) NOT NULL,
    "shipmentId" UUID,
    "warehouseId" UUID NOT NULL,
    "receiptDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "containerNumber" VARCHAR(40),
    "numberOfBales" INTEGER NOT NULL DEFAULT 0,
    "totalWeightKg" DECIMAL(18,3) NOT NULL DEFAULT 0,
    "containerCost" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "offloadingCost" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "transportCost" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "warehouseCost" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "verifiedBy" VARCHAR(140),
    "notes" VARCHAR(600),
    "isPosted" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "GoodsReceipt_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "GoodsReceiptLine" (
    "id" UUID NOT NULL,
    "goodsReceiptId" UUID NOT NULL,
    "productId" UUID NOT NULL,
    "quantity" DECIMAL(18,3) NOT NULL,
    "unitCost" DECIMAL(18,4) NOT NULL,
    "lineTotal" DECIMAL(18,2) NOT NULL,
    CONSTRAINT "GoodsReceiptLine_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Bale" (
    "id" UUID NOT NULL,
    "baleNumber" VARCHAR(40) NOT NULL,
    "goodsReceiptId" UUID NOT NULL,
    "warehouseId" UUID NOT NULL,
    "productId" UUID,
    "shoeType" VARCHAR(140) NOT NULL,
    "weightKg" DECIMAL(18,3) NOT NULL,
    "balePrice" DECIMAL(18,2) NOT NULL,
    "landedCost" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "piecesEstimate" INTEGER NOT NULL DEFAULT 0,
    "piecesSold" INTEGER NOT NULL DEFAULT 0,
    "isOpened" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Bale_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "StockTransfer" (
    "id" UUID NOT NULL,
    "reference" VARCHAR(40) NOT NULL,
    "fromWarehouseId" UUID NOT NULL,
    "toWarehouseId" UUID NOT NULL,
    "transferDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    "createdById" UUID,
    "notes" VARCHAR(400),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "StockTransfer_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "StockTransferLine" (
    "id" UUID NOT NULL,
    "transferId" UUID NOT NULL,
    "productId" UUID NOT NULL,
    "quantity" DECIMAL(18,3) NOT NULL,
    CONSTRAINT "StockTransferLine_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "StockAdjustment" (
    "id" UUID NOT NULL,
    "reference" VARCHAR(40) NOT NULL,
    "warehouseId" UUID NOT NULL,
    "reason" VARCHAR(30) NOT NULL,
    "adjustmentDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    "userId" UUID,
    "notes" VARCHAR(400),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "StockAdjustment_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "StockAdjustmentLine" (
    "id" UUID NOT NULL,
    "adjustmentId" UUID NOT NULL,
    "productId" UUID NOT NULL,
    "quantity" DECIMAL(18,3) NOT NULL,
    "unitCost" DECIMAL(18,4) NOT NULL DEFAULT 0,
    CONSTRAINT "StockAdjustmentLine_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "StockTake" (
    "id" UUID NOT NULL,
    "reference" VARCHAR(40) NOT NULL,
    "warehouseId" UUID NOT NULL,
    "takeDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    "userId" UUID,
    "notes" VARCHAR(400),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completedAt" TIMESTAMP(3),
    CONSTRAINT "StockTake_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "StockTakeLine" (
    "id" UUID NOT NULL,
    "stockTakeId" UUID NOT NULL,
    "productId" UUID NOT NULL,
    "systemQty" DECIMAL(18,3) NOT NULL,
    "countedQty" DECIMAL(18,3) NOT NULL,
    "variance" DECIMAL(18,3) NOT NULL,
    CONSTRAINT "StockTakeLine_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Customer" (
    "id" UUID NOT NULL,
    "code" VARCHAR(30) NOT NULL,
    "name" VARCHAR(160) NOT NULL,
    "phone" VARCHAR(40),
    "email" VARCHAR(160),
    "address" VARCHAR(300),
    "taxPin" VARCHAR(40),
    "creditLimit" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "balance" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Customer_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Sale" (
    "id" UUID NOT NULL,
    "reference" VARCHAR(40) NOT NULL,
    "channel" VARCHAR(30) NOT NULL DEFAULT 'POS',
    "customerId" UUID,
    "branchId" UUID,
    "cashierId" UUID NOT NULL,
    "cashSessionId" UUID,
    "saleDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "subtotal" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "discount" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "taxAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "total" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "amountPaid" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "changeGiven" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "costOfSale" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "status" VARCHAR(30) NOT NULL DEFAULT 'COMPLETED',
    "isCredit" BOOLEAN NOT NULL DEFAULT false,
    "dueDate" TIMESTAMP(3),
    "notes" VARCHAR(400),
    "voidReason" VARCHAR(300),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Sale_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "SaleLine" (
    "id" UUID NOT NULL,
    "saleId" UUID NOT NULL,
    "productId" UUID NOT NULL,
    "description" VARCHAR(300) NOT NULL,
    "quantity" DECIMAL(18,3) NOT NULL,
    "unitPrice" DECIMAL(18,2) NOT NULL,
    "discount" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "taxRate" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "taxAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "unitCost" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "lineTotal" DECIMAL(18,2) NOT NULL,
    CONSTRAINT "SaleLine_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "SalesReturn" (
    "id" UUID NOT NULL,
    "reference" VARCHAR(40) NOT NULL,
    "saleId" UUID,
    "customerId" UUID,
    "returnDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reason" VARCHAR(400),
    "totalAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "isRestocked" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "SalesReturn_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "SalesReturnLine" (
    "id" UUID NOT NULL,
    "salesReturnId" UUID NOT NULL,
    "productId" UUID NOT NULL,
    "quantity" DECIMAL(18,3) NOT NULL,
    "unitPrice" DECIMAL(18,2) NOT NULL,
    "lineTotal" DECIMAL(18,2) NOT NULL,
    CONSTRAINT "SalesReturnLine_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Receipt" (
    "id" UUID NOT NULL,
    "reference" VARCHAR(40) NOT NULL,
    "customerId" UUID,
    "saleId" UUID,
    "cashSessionId" UUID,
    "method" VARCHAR(30) NOT NULL,
    "status" VARCHAR(30) NOT NULL DEFAULT 'COMPLETED',
    "amount" DECIMAL(18,2) NOT NULL,
    "receiptDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "mpesaCode" VARCHAR(40),
    "bankReference" VARCHAR(80),
    "userId" UUID,
    "notes" VARCHAR(400),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Receipt_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Payment" (
    "id" UUID NOT NULL,
    "reference" VARCHAR(40) NOT NULL,
    "payeeType" VARCHAR(30) NOT NULL DEFAULT 'SUPPLIER',
    "supplierId" UUID,
    "payeeName" VARCHAR(160),
    "supplierInvoiceId" UUID,
    "method" VARCHAR(30) NOT NULL,
    "status" VARCHAR(30) NOT NULL DEFAULT 'COMPLETED',
    "isDeposit" BOOLEAN NOT NULL DEFAULT false,
    "currency" VARCHAR(3) NOT NULL DEFAULT 'KES',
    "exchangeRate" DECIMAL(18,6) NOT NULL DEFAULT 1,
    "amount" DECIMAL(18,2) NOT NULL,
    "amountKes" DECIMAL(18,2) NOT NULL,
    "paymentDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "bankReference" VARCHAR(80),
    "mpesaCode" VARCHAR(40),
    "userId" UUID,
    "notes" VARCHAR(400),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Payment_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ExpenseCategory" (
    "id" UUID NOT NULL,
    "name" VARCHAR(120) NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ExpenseCategory_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Expense" (
    "id" UUID NOT NULL,
    "reference" VARCHAR(40) NOT NULL,
    "categoryId" UUID NOT NULL,
    "description" VARCHAR(400) NOT NULL,
    "amount" DECIMAL(18,2) NOT NULL,
    "method" VARCHAR(30) NOT NULL DEFAULT 'CASH',
    "expenseDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "payeeName" VARCHAR(160),
    "status" VARCHAR(30) NOT NULL DEFAULT 'APPROVED',
    "userId" UUID,
    "attachmentUrl" VARCHAR(400),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Expense_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "CashSession" (
    "id" UUID NOT NULL,
    "reference" VARCHAR(40) NOT NULL,
    "userId" UUID NOT NULL,
    "openingFloat" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "closingCount" DECIMAL(18,2),
    "expectedCash" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "variance" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "status" VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    "openedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "closedAt" TIMESTAMP(3),
    "notes" VARCHAR(400),
    CONSTRAINT "CashSession_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "MpesaTransaction" (
    "id" UUID NOT NULL,
    "merchantRequestId" VARCHAR(80),
    "checkoutRequestId" VARCHAR(80),
    "mpesaReceipt" VARCHAR(40),
    "phoneNumber" VARCHAR(30) NOT NULL,
    "amount" DECIMAL(18,2) NOT NULL,
    "accountReference" VARCHAR(60),
    "saleId" UUID,
    "status" VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    "resultCode" INTEGER,
    "resultDesc" VARCHAR(300),
    "rawCallback" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "MpesaTransaction_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Role_name_key" ON "Role"("name");
CREATE UNIQUE INDEX "Permission_code_key" ON "Permission"("code");
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "User_username_key" ON "User"("username");
CREATE INDEX "User_roleId_idx" ON "User"("roleId");
CREATE INDEX "AuditLog_entity_entityId_idx" ON "AuditLog"("entity", "entityId");
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");
CREATE UNIQUE INDEX "Branch_code_key" ON "Branch"("code");
CREATE INDEX "Approval_entity_entityId_idx" ON "Approval"("entity", "entityId");
CREATE INDEX "Approval_status_idx" ON "Approval"("status");
CREATE UNIQUE INDEX "Supplier_code_key" ON "Supplier"("code");
CREATE UNIQUE INDEX "PurchaseOrder_reference_key" ON "PurchaseOrder"("reference");
CREATE INDEX "PurchaseOrder_supplierId_idx" ON "PurchaseOrder"("supplierId");
CREATE INDEX "PurchaseOrder_status_idx" ON "PurchaseOrder"("status");
CREATE INDEX "PurchaseOrderLine_purchaseOrderId_idx" ON "PurchaseOrderLine"("purchaseOrderId");
CREATE UNIQUE INDEX "SupplierInvoice_supplierId_invoiceNumber_key" ON "SupplierInvoice"("supplierId", "invoiceNumber");
CREATE INDEX "SupplierInvoice_status_idx" ON "SupplierInvoice"("status");
CREATE UNIQUE INDEX "PurchaseReturn_reference_key" ON "PurchaseReturn"("reference");
CREATE UNIQUE INDEX "ImportOrder_reference_key" ON "ImportOrder"("reference");
CREATE INDEX "ImportOrder_stage_idx" ON "ImportOrder"("stage");
CREATE UNIQUE INDEX "Shipment_reference_key" ON "Shipment"("reference");
CREATE INDEX "Shipment_importOrderId_idx" ON "Shipment"("importOrderId");
CREATE INDEX "Shipment_status_idx" ON "Shipment"("status");
CREATE UNIQUE INDEX "ClearingAgent_code_key" ON "ClearingAgent"("code");
CREATE INDEX "ImportDocument_importOrderId_idx" ON "ImportDocument"("importOrderId");
CREATE INDEX "ImportDocument_type_idx" ON "ImportDocument"("type");
CREATE INDEX "CustomsEntry_shipmentId_idx" ON "CustomsEntry"("shipmentId");
CREATE INDEX "LandedCostCharge_importOrderId_idx" ON "LandedCostCharge"("importOrderId");
CREATE INDEX "LandedCostCharge_category_idx" ON "LandedCostCharge"("category");
CREATE UNIQUE INDEX "Category_name_key" ON "Category"("name");
CREATE UNIQUE INDEX "Product_sku_key" ON "Product"("sku");
CREATE INDEX "Product_categoryId_idx" ON "Product"("categoryId");
CREATE INDEX "Product_isActive_idx" ON "Product"("isActive");
CREATE UNIQUE INDEX "Warehouse_code_key" ON "Warehouse"("code");
CREATE UNIQUE INDEX "StockLevel_productId_warehouseId_key" ON "StockLevel"("productId", "warehouseId");
CREATE INDEX "StockLevel_warehouseId_idx" ON "StockLevel"("warehouseId");
CREATE INDEX "StockMovement_productId_createdAt_idx" ON "StockMovement"("productId", "createdAt");
CREATE INDEX "StockMovement_warehouseId_idx" ON "StockMovement"("warehouseId");
CREATE INDEX "StockMovement_type_idx" ON "StockMovement"("type");
CREATE UNIQUE INDEX "GoodsReceipt_reference_key" ON "GoodsReceipt"("reference");
CREATE INDEX "GoodsReceipt_shipmentId_idx" ON "GoodsReceipt"("shipmentId");
CREATE INDEX "GoodsReceiptLine_goodsReceiptId_idx" ON "GoodsReceiptLine"("goodsReceiptId");
CREATE UNIQUE INDEX "Bale_baleNumber_key" ON "Bale"("baleNumber");
CREATE INDEX "Bale_goodsReceiptId_idx" ON "Bale"("goodsReceiptId");
CREATE INDEX "Bale_warehouseId_idx" ON "Bale"("warehouseId");
CREATE UNIQUE INDEX "StockTransfer_reference_key" ON "StockTransfer"("reference");
CREATE UNIQUE INDEX "StockAdjustment_reference_key" ON "StockAdjustment"("reference");
CREATE UNIQUE INDEX "StockTake_reference_key" ON "StockTake"("reference");
CREATE UNIQUE INDEX "Customer_code_key" ON "Customer"("code");
CREATE INDEX "Customer_isActive_idx" ON "Customer"("isActive");
CREATE UNIQUE INDEX "Sale_reference_key" ON "Sale"("reference");
CREATE INDEX "Sale_saleDate_idx" ON "Sale"("saleDate");
CREATE INDEX "Sale_customerId_idx" ON "Sale"("customerId");
CREATE INDEX "Sale_status_idx" ON "Sale"("status");
CREATE INDEX "Sale_cashierId_idx" ON "Sale"("cashierId");
CREATE INDEX "SaleLine_saleId_idx" ON "SaleLine"("saleId");
CREATE INDEX "SaleLine_productId_idx" ON "SaleLine"("productId");
CREATE UNIQUE INDEX "SalesReturn_reference_key" ON "SalesReturn"("reference");
CREATE INDEX "SalesReturn_saleId_idx" ON "SalesReturn"("saleId");
CREATE UNIQUE INDEX "Receipt_reference_key" ON "Receipt"("reference");
CREATE INDEX "Receipt_customerId_idx" ON "Receipt"("customerId");
CREATE INDEX "Receipt_receiptDate_idx" ON "Receipt"("receiptDate");
CREATE INDEX "Receipt_status_idx" ON "Receipt"("status");
CREATE UNIQUE INDEX "Payment_reference_key" ON "Payment"("reference");
CREATE INDEX "Payment_supplierId_idx" ON "Payment"("supplierId");
CREATE INDEX "Payment_paymentDate_idx" ON "Payment"("paymentDate");
CREATE UNIQUE INDEX "ExpenseCategory_name_key" ON "ExpenseCategory"("name");
CREATE UNIQUE INDEX "Expense_reference_key" ON "Expense"("reference");
CREATE INDEX "Expense_expenseDate_idx" ON "Expense"("expenseDate");
CREATE INDEX "Expense_categoryId_idx" ON "Expense"("categoryId");
CREATE UNIQUE INDEX "CashSession_reference_key" ON "CashSession"("reference");
CREATE INDEX "CashSession_userId_idx" ON "CashSession"("userId");
CREATE INDEX "CashSession_status_idx" ON "CashSession"("status");
CREATE INDEX "MpesaTransaction_status_idx" ON "MpesaTransaction"("status");
CREATE INDEX "MpesaTransaction_saleId_idx" ON "MpesaTransaction"("saleId");

-- AddForeignKey
ALTER TABLE "RolePermission" ADD CONSTRAINT "RolePermission_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "Role"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RolePermission" ADD CONSTRAINT "RolePermission_permissionId_fkey" FOREIGN KEY ("permissionId") REFERENCES "Permission"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "User" ADD CONSTRAINT "User_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "Role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "User" ADD CONSTRAINT "User_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Approval" ADD CONSTRAINT "Approval_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "PurchaseOrder" ADD CONSTRAINT "PurchaseOrder_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "PurchaseOrderLine" ADD CONSTRAINT "PurchaseOrderLine_purchaseOrderId_fkey" FOREIGN KEY ("purchaseOrderId") REFERENCES "PurchaseOrder"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PurchaseOrderLine" ADD CONSTRAINT "PurchaseOrderLine_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "SupplierInvoice" ADD CONSTRAINT "SupplierInvoice_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "SupplierInvoice" ADD CONSTRAINT "SupplierInvoice_purchaseOrderId_fkey" FOREIGN KEY ("purchaseOrderId") REFERENCES "PurchaseOrder"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "PurchaseReturn" ADD CONSTRAINT "PurchaseReturn_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "PurchaseReturnLine" ADD CONSTRAINT "PurchaseReturnLine_purchaseReturnId_fkey" FOREIGN KEY ("purchaseReturnId") REFERENCES "PurchaseReturn"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PurchaseReturnLine" ADD CONSTRAINT "PurchaseReturnLine_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "ImportOrder" ADD CONSTRAINT "ImportOrder_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "ImportOrder" ADD CONSTRAINT "ImportOrder_purchaseOrderId_fkey" FOREIGN KEY ("purchaseOrderId") REFERENCES "PurchaseOrder"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Shipment" ADD CONSTRAINT "Shipment_importOrderId_fkey" FOREIGN KEY ("importOrderId") REFERENCES "ImportOrder"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Shipment" ADD CONSTRAINT "Shipment_clearingAgentId_fkey" FOREIGN KEY ("clearingAgentId") REFERENCES "ClearingAgent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "ImportDocument" ADD CONSTRAINT "ImportDocument_importOrderId_fkey" FOREIGN KEY ("importOrderId") REFERENCES "ImportOrder"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ImportDocument" ADD CONSTRAINT "ImportDocument_shipmentId_fkey" FOREIGN KEY ("shipmentId") REFERENCES "Shipment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "CustomsEntry" ADD CONSTRAINT "CustomsEntry_shipmentId_fkey" FOREIGN KEY ("shipmentId") REFERENCES "Shipment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "LandedCostCharge" ADD CONSTRAINT "LandedCostCharge_importOrderId_fkey" FOREIGN KEY ("importOrderId") REFERENCES "ImportOrder"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "LandedCostCharge" ADD CONSTRAINT "LandedCostCharge_shipmentId_fkey" FOREIGN KEY ("shipmentId") REFERENCES "Shipment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Product" ADD CONSTRAINT "Product_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Warehouse" ADD CONSTRAINT "Warehouse_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "StockLevel" ADD CONSTRAINT "StockLevel_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "StockLevel" ADD CONSTRAINT "StockLevel_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "Warehouse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "StockMovement" ADD CONSTRAINT "StockMovement_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "StockMovement" ADD CONSTRAINT "StockMovement_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "Warehouse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "StockMovement" ADD CONSTRAINT "StockMovement_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "GoodsReceipt" ADD CONSTRAINT "GoodsReceipt_shipmentId_fkey" FOREIGN KEY ("shipmentId") REFERENCES "Shipment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "GoodsReceipt" ADD CONSTRAINT "GoodsReceipt_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "Warehouse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "GoodsReceiptLine" ADD CONSTRAINT "GoodsReceiptLine_goodsReceiptId_fkey" FOREIGN KEY ("goodsReceiptId") REFERENCES "GoodsReceipt"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "GoodsReceiptLine" ADD CONSTRAINT "GoodsReceiptLine_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Bale" ADD CONSTRAINT "Bale_goodsReceiptId_fkey" FOREIGN KEY ("goodsReceiptId") REFERENCES "GoodsReceipt"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Bale" ADD CONSTRAINT "Bale_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "Warehouse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Bale" ADD CONSTRAINT "Bale_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "StockTransfer" ADD CONSTRAINT "StockTransfer_fromWarehouseId_fkey" FOREIGN KEY ("fromWarehouseId") REFERENCES "Warehouse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "StockTransfer" ADD CONSTRAINT "StockTransfer_toWarehouseId_fkey" FOREIGN KEY ("toWarehouseId") REFERENCES "Warehouse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "StockTransfer" ADD CONSTRAINT "StockTransfer_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "StockTransferLine" ADD CONSTRAINT "StockTransferLine_transferId_fkey" FOREIGN KEY ("transferId") REFERENCES "StockTransfer"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "StockTransferLine" ADD CONSTRAINT "StockTransferLine_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "StockAdjustment" ADD CONSTRAINT "StockAdjustment_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "Warehouse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "StockAdjustment" ADD CONSTRAINT "StockAdjustment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "StockAdjustmentLine" ADD CONSTRAINT "StockAdjustmentLine_adjustmentId_fkey" FOREIGN KEY ("adjustmentId") REFERENCES "StockAdjustment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "StockAdjustmentLine" ADD CONSTRAINT "StockAdjustmentLine_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "StockTake" ADD CONSTRAINT "StockTake_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "Warehouse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "StockTake" ADD CONSTRAINT "StockTake_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "StockTakeLine" ADD CONSTRAINT "StockTakeLine_stockTakeId_fkey" FOREIGN KEY ("stockTakeId") REFERENCES "StockTake"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "StockTakeLine" ADD CONSTRAINT "StockTakeLine_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Sale" ADD CONSTRAINT "Sale_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Sale" ADD CONSTRAINT "Sale_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Sale" ADD CONSTRAINT "Sale_cashierId_fkey" FOREIGN KEY ("cashierId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Sale" ADD CONSTRAINT "Sale_cashSessionId_fkey" FOREIGN KEY ("cashSessionId") REFERENCES "CashSession"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "SaleLine" ADD CONSTRAINT "SaleLine_saleId_fkey" FOREIGN KEY ("saleId") REFERENCES "Sale"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SaleLine" ADD CONSTRAINT "SaleLine_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "SalesReturn" ADD CONSTRAINT "SalesReturn_saleId_fkey" FOREIGN KEY ("saleId") REFERENCES "Sale"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "SalesReturn" ADD CONSTRAINT "SalesReturn_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "SalesReturnLine" ADD CONSTRAINT "SalesReturnLine_salesReturnId_fkey" FOREIGN KEY ("salesReturnId") REFERENCES "SalesReturn"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SalesReturnLine" ADD CONSTRAINT "SalesReturnLine_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Receipt" ADD CONSTRAINT "Receipt_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Receipt" ADD CONSTRAINT "Receipt_saleId_fkey" FOREIGN KEY ("saleId") REFERENCES "Sale"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Receipt" ADD CONSTRAINT "Receipt_cashSessionId_fkey" FOREIGN KEY ("cashSessionId") REFERENCES "CashSession"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Receipt" ADD CONSTRAINT "Receipt_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_supplierInvoiceId_fkey" FOREIGN KEY ("supplierInvoiceId") REFERENCES "SupplierInvoice"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Expense" ADD CONSTRAINT "Expense_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "ExpenseCategory"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Expense" ADD CONSTRAINT "Expense_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "CashSession" ADD CONSTRAINT "CashSession_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Partial unique indexes & case-insensitive login (same as prisma/indexes.sql)

CREATE UNIQUE INDEX IF NOT EXISTS "UX_Product_barcode"
  ON "Product" ("barcode")
  WHERE "barcode" IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "UX_MpesaTransaction_checkoutRequestId"
  ON "MpesaTransaction" ("checkoutRequestId")
  WHERE "checkoutRequestId" IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "UX_ImportOrder_purchaseOrderId"
  ON "ImportOrder" ("purchaseOrderId")
  WHERE "purchaseOrderId" IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "UX_User_username_lower" ON "User" (lower("username"));
CREATE UNIQUE INDEX IF NOT EXISTS "UX_User_email_lower" ON "User" (lower("email"));
